### ISSUE TITLE
Allow domain whitelisting

### ISSUE THREAD

**Issue by bb010g** [ThomazPom/Moz-Ext-Ignore-X-Frame-Options#1]
I'm fine with X-Frame-Origin being used on most sites, but there are a couple sites that I do want it cleaned on, so it'd be nice if the user could specify a whitelist of domains (or maybe regexes on URLs) that the cleaning would take effect on.

**Comment by ThomazPom** [comment]
Sure, i'll implement a regexp white list, default with *

**Comment by ThomazPom** [comment]
[Implemented in this commit](https://github.com/ThomazPom/Moz-Ext-Ignore-X-Frame-Options/commit/68d8df39e3d9d7b90e48147d57cc7b79812ee7c8)

Default allowed urls :
```
http://*/*
https://*/*
```

**Comment by ThomazPom** [comment]
[App has been updated in mozilla store](https://addons.mozilla.org/fr/firefox/addon/ignore-x-frame-options-header/)

**Comment by Goury** [comment]
And how are we supposed to edit this whitelist?
Doesn't seem to be a way through the interface.

**Comment by ThomazPom** [comment]
![Image](https://pom.pm/images/misc/2wn2T5SV2y.gif)

**Comment by Goury** [comment]
Hmm..
Firefox doesn't show me this button for reasons unbeknownst to me =(

I am using 68.0.1-ubuntu

**Comment by ThomazPom** [comment]
![Image](http://pom.pm/images/misc/EbqrckMYmO.gif)

**Comment by Goury** [comment]
If only it was that easy.
I'll go hack my custom profile, most likely it's something in there.

**Comment by ThomazPom** [comment]
Tell me if you find how, i'm curious

**Comment by bb010g** [comment]
Oh yeah, got a notification for this, and not sure if you'd want to maybe allow this via a UI toggle, but if you want to take match patterns too instead of straight regexes, I ended up posting https://github.com/bb010g/match-pattern-to-regexp (CC0) while doing Anarchist Framer. (Based off of a MDN wiki function that got pulled when I edited in improvements.)

They're generally saner to read & write for URLs.

**Comment by Goury** [comment]
So I am not sure how and why, but after migrating everything to a fresh new profile it started working.

**Comment by abugher** [comment]
> And how are we supposed to edit this whitelist? Doesn't seem to be a way through the interface.

I have this question, also.  I see that @ThomazPom answered right away, but the it seems that the linked content is now 404.

**Comment by abugher** [comment]
I checked wayback machine and saw the animated responses.  The extension should create an icon ... somewhere.  The animated responses indicate that if it is missing, it might be restored using the `Customize Toolbar` feature.  I found it under a puzzle-piece icon for Extensions.

You poke the icon, and it shows you an editor.
