### ISSUE TITLE
On Off switch

### ISSUE THREAD

**Issue by mmallejac** [ThomazPom/Moz-Ext-Ignore-X-Frame-Options#11]
Very handy, thanks !
Would be great to have an on/off switch

**Comment by ThomazPom** [comment]
Please update to 1.6.1 to get this wonderful switch:
![image](https://user-images.githubusercontent.com/8494601/81418212-9c0f1e80-914c-11ea-867b-56f8b67f81e3.png)

**Comment by mmallejac** [comment]
_Magnifique_ ! many thanks
