### ISSUE TITLE
How to use the Ignore-X-Frame-Options plug-in

### ISSUE THREAD

**Issue by liujunfx** [ThomazPom/Moz-Ext-Ignore-X-Frame-Options#13]
Hello Thomaz,
I tend to embed an internal website into iframe, the html code is shown below
<!DOCTYPE html>
<html lang="zh-CN">
<head>

<title>sub window </title>
<body>

<iframe  src="https://10.128.13.46" width="1000" height="1000" style="float:right">

</iframe>

</body>
</html>

this 10.128.13.46 is the IP of my internal web server.

I don't know if I need input anything into the plug-in.

![图片](https://user-images.githubusercontent.com/17546452/85485754-eca6e200-b5fb-11ea-9c4b-5e3da3e48914.png)

**Comment by ThomazPom** [comment]
I suspect a bug in firefox itself and i opened an issue here
https://bugzilla.mozilla.org/show_bug.cgi?id=1648105
For your specific case, if you want a quick fix i suggest you to use the previous 1.5.4 of the plug-in
It was working in another way which i didn't like but was not affected by this issue.
https://addons.mozilla.org/fr/firefox/addon/ignore-x-frame-options-header/versions/

Thanks for the report
Thomas

**Comment by liujunfx** [comment]
Thamos,
        Thank you very much! you did me great favour!

Richard


________________________________

**Comment by liujunfx** [comment]
Thomas,
         Thank you very much! you did me great favour!

Richard

________________________________

**Comment by liujunfx** [comment]
Thomaz,
Will this plug-in upgrade automatically? I used V1.5.4 and it worked well, but suddently I found it was upgraded. I did nothing on it.

Richard

________________________________

**Comment by ThomazPom** [comment]
As far as i know, this is not suposed to happen.

**Comment by ThomazPom** [comment]
Hi, i worked hard & solved your bug in the latest **1.6.5** version.
Can you confirm this is working for you ?

https://addons.mozilla.org/fr/firefox/addon/ignore-x-frame-options-header/versions/

**Comment by liujunfx** [comment]
Thomaz,
            Thank you so much. One problem about upgrade again, before I upgraded to 1.6.5 I found it had been upgraded from 1.5.4 to new version again, so I removed it and installed the latest 1.6.5. this is really weird.

Richard

________________________________

**Comment by ThomazPom** [comment]
As long the 1.6.5 solved your issue, i'm closing this thread
Again, thank you for seeing this :) I think this a bug  affected a lot of people using this webext
