### ISSUE TITLE
Stopped working in Firefox 56.0.1 since 1.6.0

### ISSUE THREAD

**Issue by izogfif** [ThomazPom/Moz-Ext-Ignore-X-Frame-Options#14]
This add-on stopped working in Firefox 56.0.1 (64-bit) on Windows since the version 1.6.0. Version 1.5.4 still works.

**Comment by ThomazPom** [comment]
Hi.
Version 1.6.0 may be very buggy as i reworked a lot of stuff in this release.
Did you tried with the last version, 1.6.8 ?

**Comment by izogfif** [comment]
Yes. Tried this:

- Downloaded Firefox Portable 56.0.1 from this page: https://sourceforge.net/projects/portableapps/files/Mozilla%20Firefox%2C%20Portable%20Ed./Mozilla%20Firefox%2C%20Portable%20Edition%2056.0.1/
- Installed the latest version of the add-on.
- Went to https://www.w3schools.com/code/tryit.asp?filename=GEFNSY7F440P page to test and clicked "Run" button.
- On the right side there were no iframes loaded. In the console there are lots of error messages about x-frame-options forbidding embedding.

**Comment by ThomazPom** [comment]
Oh, thank you for this . I will reproduce and tell you.

**Comment by ThomazPom** [comment]
This was a bug of this addon on old versions of firefox.
I made the code of the 1.6.9 (and above) backward compatible.

Please confirm this is working in your firefox 56

**Comment by izogfif** [comment]
Works now. Thanks.

**Comment by ThomazPom** [comment]
Good
