### ISSUE TITLE
Invalid tabId with objects

### ISSUE THREAD

**Issue by gunjambi** [ThomazPom/Moz-Ext-Ignore-X-Frame-Options#16]
With an embed flash object, I get `tabId == -1` in `setHeader`. This then throws in `webNavigation::getFrame`.

See the PR for a originUrl-based workaround.

**Comment by ThomazPom** [comment]
Does [this edit](https://github.com/ThomazPom/Moz-Ext-Ignore-X-Frame-Options/commit/427798fd4b846606d82fadca52b2ab2f550fbe5e#diff-f9b12bd72f40c9b8ed144484f0f12a5f) fixes this bug ?
There is a precise reason why i stopped using originUrl.
I'll try to recall .

**Comment by ThomazPom** [comment]
According to [this](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onHeadersReceived#Browser_compatibility) , originUrl is only available in FireFox.
Thats probably why i choose to use the tabid and the parentFrameId

**Comment by ThomazPom** [comment]
[Edit 2 ](https://github.com/ThomazPom/Moz-Ext-Ignore-X-Frame-Options/commit/b5f01a048d5b95f04ee5dd90f2cc94e083d239f1), bug fix

**Comment by gunjambi** [comment]
Tested. The Edit 2 ( b5f01a048d5b95f04ee5dd90f2cc94e083d239f1 ) fixes the bug for me.
