### ISSUE TITLE
Some sites are not working

### ISSUE THREAD

**Issue by mageshr26** [ThomazPom/Moz-Ext-Ignore-X-Frame-Options#18]
Hi,
I tried to load Netflix inside an iFrame, Im getting login screen but I cant able to login and play video inside iFrame itself, can you help me to load Netflix in a iFrame.
Thanks in advance

**Comment by ThomazPom** [comment]
Hi
I checked your issue.
This is due to strong netflix security measures i can't get trough

If your need is to embed netflix, i recommend you to use a small electron app instead
https://www.electronjs.org/docs/api/browser-window

I'm sorry Moz-Ext-Ignore-X-Frame-Option can't solve this issue

**Comment by mageshr26** [comment]
Hi
I checked out electron app 
But I'm actually trying to load Netflix inside an iFrame in web application,
Can you recommend any other way

Thanks

**Comment by ThomazPom** [comment]
I found out any web extension has an url in the form of
moz-extension://<EXTENSION INSTALL ID>/file.html 

I found out a web extension witch edits requests like Moz-Ext-Ignore-X-Frame-Options can load any url with any restriction in its own pages

You may want to fork this extension and put your custom html (with iframes) in a parent.html file and access it directly 
moz-extension:/<EXTENSION INSTALL ID>/file.html
