### ISSUE TITLE
Thanks for the great JOB

### ISSUE THREAD

**Issue by Hedi2** [ThomazPom/Moz-Ext-Ignore-X-Frame-Options#19]
It's just Dream :):):)
Do you think it is possible that one can integrate a JS version in the HTML Webpage (Preferably AMP one) 
without having to ask the user to add the "Ignore X-Frame" extension to the Browser.
I display many suppliers tech doc and INFO for my customers (who are resellers for this manufacturers).
Iframe allows me have my customer's website updated with the latest Products list and specs of the manufacturer.
Asking 20 worldwide suppliers to whitelist me in the CSP  is difficult

It is just Dreaming load  :):):)
have a nice day
Hedi

**Comment by ThomazPom** [comment]
Hi
Short answer : You can't do it in pure browser client javascript

The only way to go without extension is to write a server side browser that acts like a proxy
https://www.phpclasses.org/package/1155-PHP-Browsing-the-Web-via-PHP.html
and drops some headers, like this.
https://stackoverflow.com/questions/61566173/i-need-to-remove-or-ignore-the-x-frame-options-header-should-i-use-a-proxy
This has been already done for other headers (CORS anywhere)
https://github.com/Rob--W/cors-anywhere
However you'll lost cookies and tracking among the way, unless you do complicated stuff to map them

**Comment by ThomazPom** [comment]
This would take minutes to fork and edit https://github.com/Rob--W/cors-anywhere/blob/master/server.js to add x frame options to dropped headers btw
