### ISSUE TITLE
Add support for frame-ancestors

### ISSUE THREAD

**Issue by phts** [ThomazPom/Moz-Ext-Ignore-X-Frame-Options#2]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors

**Comment by ThomazPom** [comment]
Hey, i just released V1.4 including this in 
https://github.com/ThomazPom/Moz-Ext-Ignore-X-Frame-Options/commit/a25b5770998d4c427570dc9a75a3243e90105178.
Please update & try, then tell me if it work for you
