### ISSUE TITLE
Doesn't work with extensions

### ISSUE THREAD

**Issue by Gnopps** [ThomazPom/Moz-Ext-Ignore-X-Frame-Options#21]
Thanks for developing this! I've got a webpage with an iframe that shows as part of a Firefox add-on, and in htat page this add-on doesn't work. 

The address of the webpage is moz-extension://0ceaa7ee-91fc-46c2-fa10-d935fc30b8a2/app/webext.html so it should be allowed through with the default filter but is not. Do you think there is anything that can be done about this?

**Comment by ThomazPom** [comment]
Hi, 

I tried. This is not possible.

I suggest you to do the opposite :

Use the source code of the app

Import Moz-Ext-Ignore-X-Frame-Options source code in its background to allow the ext to truly load anything

add iframes to /app/webext.html
( Or create a parent.html  page  and load /app/webext.html amogn other websites)  

load app/webext.html (or parent.html ) with your custom layout
