### ISSUE TITLE
Extension seems to not be working on Firefox Beta 111.0

### ISSUE THREAD

**Issue by jairrencora** [ThomazPom/Moz-Ext-Ignore-X-Frame-Options#22]
Seems the latest Firefox Beta breaks the extension. I had been using the extension for a few days and after updating it has not been working.

Error in console: The loading of “https://www.youtube.com/” in a frame is denied by “X-Frame-Options“ directive set to “SAMEORIGIN“

Tested using the test w3schools test page, just changing the url. To my knowledge no other change besides the browser version has happened

**Comment by ThomazPom** [comment]
Thank you, i’ll fix asap

**Comment by ThomazPom** [comment]
Hey @jairrencora 

I just tested the web extension with firefox 111 beta 6 without any issues. Are you able to share your whitelist ?

![image](https://user-images.githubusercontent.com/8494601/221670172-27904bc6-fd2a-41ca-a648-7a6c8ec18185.png)

**Comment by jairrencora** [comment]
Hello @ThomazPom . I'm using the default settings. Could you try changing the iframe's src to "https://www.youtube.com"? Just realized it does work for the other sites, but it's failing with Youtube iFrames. And it was working for me before the update.
![image](https://user-images.githubusercontent.com/89474643/221679715-40ad3380-1212-4248-ba59-52a5d6f3f1a3.png)

**Comment by ThomazPom** [comment]
I'm sorry to inform you it works in 111 beta 6. What is your beta version?

What is exactly the error message ?

![image](https://user-images.githubusercontent.com/8494601/221690694-f7853a1e-dbae-470b-a6a1-62f4a96773de.png)

**Comment by jairrencora** [comment]
Ok. This is super weid. I downloaded a Portable version to test and it works properly on Youtube, but on my installed it refuses to load. Checked all settings, tried removing and reinstalling the addon, tried disabling other extensions, still not working. So I don't know what it is, but it seems I was wrong it was due to the update. Apologies

**Comment by ThomazPom** [comment]
Works on firefox 120
