### ISSUE TITLE
Feature request: allow whitelisting based on main document location and not on frame src

### ISSUE THREAD

**Issue by Goury** [ThomazPom/Moz-Ext-Ignore-X-Frame-Options#4]
Subj.
Because it is still a security risk to force something that doesn't want to go in a frame into frame.
So instead of allowing for any page to frame one particular website it would be nice to be able to allow one particular page to be able to frame some or any websites.

Use case: I want to make a personal page with few frames to organize some stuff for myself.

**Comment by ThomazPom** [comment]
Implemented in [This commit](https://github.com/ThomazPom/Moz-Ext-Ignore-X-Frame-Options/commit/d0b5c34a9902c36374bf61ccc9394601f68c7898)

You may reinstall the ext via the mozilla store to get the update immediatly

**Comment by ThomazPom** [comment]
Looked a bit, and released a version which meets more your requirements
https://github.com/ThomazPom/Moz-Ext-Ignore-X-Frame-Options/tree/allow_tab_to_frame_anything
