### ISSUE TITLE
Firefox 69 breaks this methinks

### ISSUE THREAD

**Issue by hypyke** [ThomazPom/Moz-Ext-Ignore-X-Frame-Options#5]
When using this plugin, current, and FF69, sites that did load WITHOUT the plugin stop working and those that needed this plugin don't work either.

I get "Blocked by content security policy".  I disable the plugin and all sites that didn't need it, IE that allow framing work again, and the one that DID need it stop working (of course)

When I say do or don't need this plugin I mean to work in frames.

Thxs

**Comment by ThomazPom** [comment]
Hey
Than you for your report, i’ll try with ff 69 asap and fix

**Comment by ThomazPom** [comment]
Hey. I tested with ff69 and all worked.
Can you share a website or a code sample where this "Blocked by content security policy" occurs ? 
Thxs  😊

**Comment by hypyke** [comment]
Unfortunately it's internal only.  The app is Organizr with other internal resources loading in iframes. It's odd that it breaks ALL frames in Organizr not just ones that don't allow framing.

![2019-09-05 12_05_45-SabNzbd - Organizr V2](https://user-images.githubusercontent.com/3076893/64359120-b9945300-cfd5-11e9-9548-2005eab13f61.png)
![2019-09-05 12_06_02-SabNzbd - Organizr V2](https://user-images.githubusercontent.com/3076893/64359122-bac58000-cfd5-11e9-86ac-e7c6236704c2.png)

**Comment by ThomazPom** [comment]
Can you share me :
The CSP header of the blocked response (you can find it in the network tab)
![image](https://user-images.githubusercontent.com/8494601/64369956-a907cb00-d01d-11e9-8c0c-427512ed550e.png)

Your "Websites allowed to frame them" setting
default is
```
http://*
https://*
file://*
```
![image](https://user-images.githubusercontent.com/8494601/64370018-d18fc500-d01d-11e9-8def-e32f992cec72.png)

**Comment by hypyke** [comment]
I've included headers from both the root app:
http://192.168.1.100:9001/
And the site it's trying to frame
http://192.168.1.100:8181/

![2019-09-05 17_04_24-](https://user-images.githubusercontent.com/3076893/64380799-be6dfc80-cfff-11e9-9d54-05bd63a5993e.png)
![2019-09-05 17_04_39-](https://user-images.githubusercontent.com/3076893/64380801-c037c000-cfff-11e9-8810-42f8c6042592.png)
![2019-09-05 17_06_21-](https://user-images.githubusercontent.com/3076893/64380806-c2018380-cfff-11e9-91ab-002d5636deb4.png)

**Comment by hypyke** [comment]
FYI:  I also created a new clean FF browser profile with no add-ons and tried it as well and I get the same issue.  Just in case it was two add-ons colliding.

**Comment by ThomazPom** [comment]
I tried in all possible ways, with ip in address bar, and tested with non 443/80 ports.
I still can't reproduce your issue.
This error can be shown in only one case, when the child frame set the CSP header with a blocking value frameancestors. (which exactly this webext targets)

Please try to set these extremely wide expressions
```
<all_urls>
```
```
*
```
If it still don't work, i will add a checkbox to disable the frame ancestor part

![image](https://user-images.githubusercontent.com/8494601/64472641-de1d3600-d161-11e9-975c-4c51c2ebf358.png)

**Comment by ThomazPom** [comment]
Please also try the 1.2 version available here, which only edit X_frame_option
https://addons.mozilla.org/fr/firefox/addon/ignore-x-frame-options-header/versions/

**Comment by erratos** [comment]
Hi, I have the same issue with Organizr and FF69.
I have tried the wide expressions and the 1.2 version. And the two works.
And even just adding the `http://url:port/*` of Organizr to the "websites allowed to frame" works... 
Maybe the default `http://*` doesn't allow every ports.

**Comment by hypyke** [comment]
@fluxtendu 
Yeah that worked for me!

![2019-09-09 17_22_17-](https://user-images.githubusercontent.com/3076893/64567520-6ea47380-d326-11e9-9d23-af93865e0984.png)

**Comment by ThomazPom** [comment]
Great 
For the knwoledge, could you pls try with`
```
http://*:*/*
```
Thank you

**Comment by hypyke** [comment]
YUP!  I removed my entry and substituted ` http://*:*/` and all my sites still work.  

I wonder why the browser upgrade made that necessary?  Odd.

Thanks for the help @ThomazPom and @fluxtendu

**Comment by GammaC0de** [comment]
Hello,

This happens for me also with the latest (1.5.3) plugin version.
How to reproduce:
- Search google for the term "iphone xs lower screen" (without the quotes)
- The first result is a div with a picture leading to a youtube video
- Click on the picture (do not click on the link)
- You get the below result:
![Untitled](https://user-images.githubusercontent.com/11036551/65326386-02453200-dbba-11e9-867e-03d3cb83bdfc.png)

**Comment by GammaC0de** [comment]
Also, try loading this web page using the default plugin setting:
``` html
<html>
  <body>
  <iframe src="https://www.google.com" height="800" width="800">
  </body>
</html>
```

You get a "Blocked by Content Security Policy" message (just as the above screenshot).


With plugin version 1.4.1 it works OK.

**Comment by ThomazPom** [comment]
I tested your code [here](https://www.w3schools.com/code/tryit.asp?filename=G88XKQ87JD4L) and [here](https://jsfiddle.net/pxeh8bo2/) and it worked with default settings
![image](https://user-images.githubusercontent.com/8494601/65380208-ac19e100-dcd6-11e9-8da3-ef96e2d8d8bf.png)

**Comment by ThomazPom** [comment]
![image](https://user-images.githubusercontent.com/8494601/65380226-f26f4000-dcd6-11e9-96b3-de42a5fa0c57.png)

**Comment by GammaC0de** [comment]
You are right,
Iit seems that you have to use a local IP address (or maybe **an** IP address?) to get blocked (see screenshot).
I used [miniweb](https://sourceforge.net/projects/miniweb/) to test.

As for https://github.com/ThomazPom/Moz-Ext-Ignore-X-Frame-Options/issues/5#issuecomment-533529768 issue, 
notice the non-default settings - with the default setting the issue does not occur.


![Untitled](https://user-images.githubusercontent.com/11036551/65380567-afb56400-dce6-11e9-90d2-9932aba7fcfa.png)

**Comment by ThomazPom** [comment]
Please try [this](https://github.com/ThomazPom/Moz-Ext-Ignore-X-Frame-Options/issues/5#issuecomment-529677980) 
I will set this as default setting in a few time

**Comment by ThomazPom** [comment]
I edited the default whitelist for your cases in f12e81f089c5bdc20ca854900a5fc62228c0f59a
I updated the webext to  v1.5.4 on the [mozilla store](https://addons.mozilla.org/fr/firefox/addon/ignore-x-frame-options-header/)
Please uninstall then reinstall the webext if you want to get default settings
New defaults are :
```
http://*
http://*:*
https://*
https://*:*
file://*
```

**Comment by GammaC0de** [comment]
Sorry for late response,
Indeed this solves the issue with the new default settings, but:
If I set only http://127.0.0.1:7000/* to "websites allowed to frame them" (as in https://github.com/ThomazPom/Moz-Ext-Ignore-X-Frame-Options/issues/5#issuecomment-533529768 screenshot),
Some iframes that shouldn't have been blocked, gets blocked by CSP.

**Comment by ThomazPom** [comment]
This is because your whitelist regex (the first one) is too broad and includes any frame. Then only your localhost could frame them

**Comment by GammaC0de** [comment]
>This is because your whitelist regex (the first one) is too broad and includes any frame. Then only your localhost could frame them

Most probably so,
but I think the right behavior for the settings in https://github.com/ThomazPom/Moz-Ext-Ignore-X-Frame-Options/issues/5#issuecomment-533529768 screenshot should mean "remove the `X-Frame-Options` header for any framed site if the site that tries to frame the is http://127.0.0.1:7000/*", other sites should work as normal,
no?

**Comment by ThomazPom** [comment]
No, this means
« enable the webext/header edition on these websites »

**Comment by GammaC0de** [comment]
So if I want to remove the `X-Frame-Options` header for any framed site if the site that tries to frame the is http://127.0.0.1:7000/*" and other sites should work as normal,
Ho do I do that?

**Comment by ThomazPom** [comment]
You can’t, because this webext replaces the policy of any website placed in the first box

Your case would mean to rather than replacing, append the rule to the csp header

**Comment by ThomazPom** [comment]
@GammaC0de 
Looked a bit, and released a version which meets your requirements
https://github.com/ThomazPom/Moz-Ext-Ignore-X-Frame-Options/tree/allow_tab_to_frame_anything

**Comment by GammaC0de** [comment]
Thank you very much, I will test it soon.

**Comment by GammaC0de** [comment]
>No, this means
« enable the webext/header edition on these websites »

> You can’t, because this webext replaces the policy of any website placed in the first box

Can you please explain what is the use case to put something else other than the defaults in `websites allowed to frame them` when using the current implementation?

**Comment by ThomazPom** [comment]
I would answer
Open one website a little bit wider :
Allow google and your website to frame a *.google website. But don't allow all websites to frame *.google ?
I personaly don't use my webext
Did you tryed the version i released for you ?

**Comment by ThomazPom** [comment]
I agree that this webext do things upside down, and this is not great.
Instead of having a website allowed to frame anything, we have websites allowed to be framed by any site.
https://github.com/ThomazPom/Moz-Ext-Ignore-X-Frame-Options/tree/allow_tab_to_frame_anything
Is better for many use cases

**Comment by GammaC0de** [comment]
> Instead of having a website allowed to frame anything, we have websites allowed to be framed by any site

Ah,  now I understand 

>Did you tried the version i released for you ?

I finally had the time to test and I *think* I found some bugs, I will update when I have a conclusion.

**Comment by GammaC0de** [comment]
Also this is a great opportunity for me to learn some webext programming ;)

**Comment by GammaC0de** [comment]
Here is what I came up with, please tell me what you think:
https://github.com/GammaC0de/Moz-Ext-Ignore-X-Frame-Options/tree/allow_tab_to_frame_anything

**Comment by ThomazPom** [comment]
@GammaC0de Very nice, the code is prettier.
By looking at the code code, i can tell you have a bug in `monitorTabRemoved` cause the way you are using filter.
After the call of `monitorTabRemoved`, watch_tabs wil ever include only one id, the one you wanted to remove. Other ids will stop from being monitored

**Comment by GammaC0de** [comment]
OK, 
Fixed, thank you.
