### ISSUE TITLE
Google Maps only half-working

### ISSUE THREAD

**Issue by amaury1093** [ThomazPom/Moz-Ext-Ignore-X-Frame-Options#6]
Hey, thanks for this extension!

I'm building a super simple website, which given a `url?=` query param, shows said url in an iframe: [github repo](https://github.com/withinreason/incognitoweb/blob/master/src/pages/index.tsx).

Here's the deployed version, if you want to try Google Maps:
https://withinreason.github.io/incognitoweb/?url=https%3A%2F%2Fwww.google.com%2Fmaps

Without your extension (which I'm trying on FF), it shows a blank page, that's expected.

With your extension, it shows Google Maps, but doesn't seem to be working well:
- I always see Loading on the bottom
- I cannot click
- I cannot search

Do you know where this comes from?

Thanks.

<img width="1381" alt="Screenshot 2019-09-23 at 15 11 07" src="https://user-images.githubusercontent.com/1293565/65440243-b8ae4e80-de28-11e9-9977-a0283180aee3.png">

**Comment by ThomazPom** [comment]
Inside the frame, google maps fails to load ressources with the access control allow origin header, then errors occurs.

You may use another webext to force this value at `*` : `Access-Control-Allow-Origin: *`
(I didnt managed to get it working, this is strange)

However, the truth is : You are trying to embed google maps the wrong & hard way

Google already share a proper method to embed google maps
The steps to get this working are

- Getting an api key, folowing [this steps](https://developers.google.com/maps/documentation/embed/get-api-key)
- Copy/paste any code from [there](https://developers-dot-devsite-v2-prod.appspot.com/maps/documentation/javascript/examples/places-searchbox) and replace `YOUR_API_KEY` by yours
- Tweak the code to get it pretty or use multiple tools on your embed like : add a search bar, add a menu, add specific text when clicked on a location ..


[Here](
https://developers-dot-devsite-v2-prod.appspot.com/maps/documentation/javascript/examples/places-searchbox) is an example of your embed integrated properly, with the search bar and [here](
https://developers-dot-devsite-v2-prod.appspot.com/maps/documentation/javascript/examples/places-autocomplete-directions) with a very cool pathfinder.

You should build your own embeds starting very simply from [there](https://developers.google.com/maps/documentation/javascript/adding-a-google-map) and picking only what you need.

Thomaz.

**Comment by amaury1093** [comment]
Thanks, I'll play with `Access-Control-Allow-Origin: *` too.

I'm aware of the embed method, but that's not what I'm looking for.

**Comment by amaury1093** [comment]
Played with `Access-Control-Allow-Methods: *` and `Access-Control-Allow-Origin: *`. Tried on Chrome too, with no success, still the same loading behavior...

Here's the output on Chrome:
```
maps:1 Blocked autofocusing on a form control in a cross-origin subframe.
maps:13 Uncaught DOMException: Blocked a frame with origin "https://www.google.com" from accessing a cross-origin frame.
    at Object._.Hr (https://www.google.com/maps/_/js/k=maps.m.en.dc5HEiFGHqQ.O/m=sc2,per,mo,lp,ti,ds,stx,bom,b/rt=j/d=1/rs=ACT90oFcxIV8Ad7kvBMCB_zNoSobKCZYEw:210:51)
    at /maps/_/js/k=maps.m.en.dc5HEiFGHqQ.O/m=vwr,vd,a,owc,ob,sp,en,smi,sc,vlg,log,smr,as,wrc/rt=j/d=1/ed=1/exm=sc2,per,mo,lp,ti,ds,stx,bom,b/rs=ACT90oFcxIV8Ad7kvBMCB_zNoSobKCZYEw:3599:3
    at /maps/_/js/k=maps.m.en.dc5HEiFGHqQ.O/m=vwr,vd,a,owc,ob,sp,en,smi,sc,vlg,log,smr,as,wrc/rt=j/d=1/ed=1/exm=sc2,per,mo,lp,ti,ds,stx,bom,b/rs=ACT90oFcxIV8Ad7kvBMCB_zNoSobKCZYEw:4990:3
    at NLa (https://www.google.com/maps/_/js/k=maps.m.en.dc5HEiFGHqQ.O/m=sc2,per,mo,lp,ti,ds,stx,bom,b/rt=j/d=1/rs=ACT90oFcxIV8Ad7kvBMCB_zNoSobKCZYEw:1677:132)
    at LLa.next (https://www.google.com/maps/_/js/k=maps.m.en.dc5HEiFGHqQ.O/m=sc2,per,mo,lp,ti,ds,stx,bom,b/rt=j/d=1/rs=ACT90oFcxIV8Ad7kvBMCB_zNoSobKCZYEw:1676:469)
    at IIa.f [as H] (https://www.google.com/maps/_/js/k=maps.m.en.dc5HEiFGHqQ.O/m=sc2,per,mo,lp,ti,ds,stx,bom,b/rt=j/d=1/rs=ACT90oFcxIV8Ad7kvBMCB_zNoSobKCZYEw:1561:184)
    at RIa (https://www.google.com/maps/_/js/k=maps.m.en.dc5HEiFGHqQ.O/m=sc2,per,mo,lp,ti,ds,stx,bom,b/rt=j/d=1/rs=ACT90oFcxIV8Ad7kvBMCB_zNoSobKCZYEw:1556:332)
    at eJa (https://www.google.com/maps/_/js/k=maps.m.en.dc5HEiFGHqQ.O/m=sc2,per,mo,lp,ti,ds,stx,bom,b/rt=j/d=1/rs=ACT90oFcxIV8Ad7kvBMCB_zNoSobKCZYEw:1565:43)
    at vA.Ma (https://www.google.com/maps/_/js/k=maps.m.en.dc5HEiFGHqQ.O/m=sc2,per,mo,lp,ti,ds,stx,bom,b/rt=j/d=1/rs=ACT90oFcxIV8Ad7kvBMCB_zNoSobKCZYEw:1564:405)
```

**Comment by ThomazPom** [comment]
at some point of the code, google maps delares a function called `_.Fr` which looks like this
```
_.Fr = function (a, b, c) {
      a = a.split('.');
      c = c || _.Dr;
      a[0] in c || 'undefined' == typeof c.execScript || c.execScript('var ' + a[0]);
      for (var d; a.length && (d = a.shift()); ) a.length || void 0 === b ? c[d] && c[d] !== Object.prototype[d] ? c = c[d] : c = c[d] = {
      }
       : c[d] = b
    };
```
Where `c` is window.top, which fail

You'll have to override on the fly this function with this code to get it working
```
_.Fr = function (a, b, c) {

      c=window.self; // Set window. self instead of c
      a = a.split('.');
      c = c || _.Dr;
      a[0] in c || 'undefined' == typeof c.execScript || c.execScript('var ' + a[0]);
      for (var d; a.length && (d = a.shift()); ) a.length || void 0 === b ? c[d] && c[d] !== Object.prototype[d] ? c = c[d] : c = c[d] = {
      }
       : c[d] = b
    };
```
Here is an example of [Tampermonkey ](https://addons.mozilla.org/fr/firefox/addon/tampermonkey/)script which fixes this for you
```
// ==UserScript==
// @name         Google maps frame fix
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You

// @run-at document-start
// @match        https://www.google.com/*
// @grant        none
// ==/UserScript==

setInterval(function(){

_.Fr = function (a, b, c) {

      c=window.self; // Set window. self instead of c
      a = a.split('.');
      c = c || _.Dr;
      a[0] in c || 'undefined' == typeof c.execScript || c.execScript('var ' + a[0]);
      for (var d; a.length && (d = a.shift()); ) a.length || void 0 === b ? c[d] && c[d] !== Object.prototype[d] ? c = c[d] : c = c[d] = {
      }
       : c[d] = b
    };

},50)
```

**Comment by ThomazPom** [comment]
![image](https://user-images.githubusercontent.com/8494601/65782754-a432c480-e14e-11e9-85cd-4f8abee5358c.png)

**Comment by amaury1093** [comment]
Nice! I just tried with your extension + the tappermonkey script, but still the loading message. Did you use another extension to modify `Access-Control-Allow-Origin: *` too?

**Comment by ThomazPom** [comment]
There were a problem with the userscript cause google obfuscate their js per user
here is a new version, improved.
```
// ==UserScript==
// @name         Google maps frame fix
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You

// @run-at document-start
// @match        https://www.google.com/*
// @grant        none
// ==/UserScript==
var interval = setInterval(function() {

    Object.keys(_).forEach(function(e) {
        var f = _[e];
        if (typeof f === "function") {
            var s = f.toSource();
            if (s.includes("(function(a,b,c){a=a.split(\".\");")) {
                _[e] = eval(s.replace("c=c||_.", "c=_."))
                clearInterval(interval)
            }
        }
    })
}, 50)
```

**Comment by amaury1093** [comment]
Wow, this works! Thanks a lot @ThomazPom.

Just out of curiosity, how did you figure that c was `window.top` in the first `_.Fr` function?

**Comment by ThomazPom** [comment]
1. - Clicked on the file generating error
![image](https://user-images.githubusercontent.com/8494601/65796971-53cb5f00-e16e-11e9-8c98-ddec965be39a.png)
2. - Pretified the file
![image](https://user-images.githubusercontent.com/8494601/65797053-837a6700-e16e-11e9-85fe-b00fd1e02b5a.png)

3. - Re click on the file err
![image](https://user-images.githubusercontent.com/8494601/65797106-ad338e00-e16e-11e9-8339-7f7836759958.png)
![image](https://user-images.githubusercontent.com/8494601/65797147-c6d4d580-e16e-11e9-8f93-cd94007f0833.png)

4. Override the found function with tampermonkey :
```
 setInterval(function() {

    _.Gr = function(a, b, c) {
        console.log("a", a, "b", b, "c", c)
    }
}, 50)
```
5. 
![image](https://user-images.githubusercontent.com/8494601/65797493-a6f1e180-e16f-11e9-8e3d-e13c67cf0313.png)
