### ISSUE TITLE
Permission denied to access property cross-origin object

### ISSUE THREAD

**Issue by boesie** [ThomazPom/Moz-Ext-Ignore-X-Frame-Options#7]
Hi, 

I Use your Firefox addon. But I still get the error:
SecurityError: Permission denied to access property "<JAVASCRIPT>" on cross-origin object.

How can I solve this problem?

**Comment by krystian3w** [comment]
`csp.enabled`  change to `false`?

**Comment by ThomazPom** [comment]
Hey,
This is not the purpose of this web ext

I recommend you to write a small tampermonkey script:

parent [post a message](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) to child iframe telling him what to do

child iframe does what parent ask and return result

sorry for my bad english
