### ISSUE TITLE
Prevents loading of some webpages

### ISSUE THREAD

**Issue by DracoBengali86** [ThomazPom/Moz-Ext-Ignore-X-Frame-Options#8]
Noticed that while the extension is active there are a few VerizonWireless.com account pages that don't load.
When the Add-on is enabled, there are multiple "Content Security Policy: The page’s settings blocked the loading of a resource at" errors.
It's the same error if you have no-script and don't have verizonwireless.com and vzw.com trusted.

**Comment by DracoBengali86** [comment]
Apologies, forgot about whitelisting by clicking the icon.
Whitelisting "\*verizonwireless.com" and possibly "\*verizon.com" fixed the issue.
Or changing the defaut whitelest "http://\*/\*" to "http://\*" also fixes the issue.

Not sure which is better, but either works.

**Comment by ThomazPom** [comment]
Hey.
This webext is far from perfect.
Instead of allowing some(/any) websites to frame some (/any) other,
it allow some(/any) website sto be framed by some(/any) other.

This "upside down" whitelist" is very restrictive and not much adaped to other uses cases than allow all to all ...

**Comment by ThomazPom** [comment]
I finally fixed this architectural issue i got from the begining,

You can update to the new version from the mozilla store

**Comment by ThomazPom** [comment]
I just published the 1.6.0, it fixes somme bugs and architectural issues please retry.
